name: WakaTime stat update in README.md

on:
  push:
    branches: [ master ]
  schedule:
    # Runs at 12 am IST
    - cron: '31 18 * * *'

jobs:
  update-readme:
    name: Update the WakaTime Stat
    runs-on: ubuntu-latest
    steps:
      - uses: avinal/README-Python-Experiment@master
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
